version: '3.8'

services:
  images.api:
    image: images.api
    build:
      context: .
      dockerfile: src/Images.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db1;Port=5432;Database=postgres;Username=postgres;Password=Upik@123
    networks:
      - upik_net
    ports:
      - 8080:8080

networks:
  upik_net:
    external: true